### ISSUE TITLE
Rename vote to non-nil-vote

### ISSUE THREAD

**Issue by junha1** [postech-dao/simperby#117]
Due to the special property of Vetomint, it's common to refer both nil votes and non nil votes.
Here we decided the naming rule that is applied universally throughout our project.

1. Nil vote (NilPrevote, NilPrecommit): the vote for skipping the round.
2. Non nil vote (NonNilPrevote, NonNilPrecommit): the vote for the proposal
3. Vote (Prevote, Precommit): either nil vote or non nil vote.

**Comment by P1n3tree** [comment]
This PR https://github.com/postech-dao/simperby/pull/126 resolves it.
