### ISSUE TITLE
Tracking issue for the consensus candidate `interactive-tendermint`

### ISSUE THREAD

**Issue by junha1** [postech-dao/simperby#17]
This is a variation of the Tendermint protocol, with few small tweaks.

1. There is no round timeout. This breaks liveness, but it doesn't really matter because we don't produce block regularly anyway (we even assume that almost every participating nodes stay offline for most of the time)
1. Pre-vote and Nil-vote are **interactive**. That is, validators (human) will be requested whether to pre-vote or nil-vote for the given received block proposal. Since there is no timeout, nil-vote is not automatically performed and can be used as a 'veto' as well. Pre-commit will be automatically performed if the user has decided to pre-vote.
1. The leader round robin order is specified in the blockchain state, and this order won't be shuffled for each block. This is for the stable leader, which makes the consensus process efficient for our case. Note that the order can be explicitly changed by a transaction anyway.

**Comment by P1n3tree** [comment]
https://docs.tendermint.com/v0.34/tendermint-core/configuration.html
There is a configuration such as "create_empty_blocks = (false/true)". They state it as "if false, blocks are created when transactions received".
But I don't know how timeout be changed in this configuration.

**Comment by junha1** [comment]
We use `vetomint` instead.
