### ISSUE TITLE
Add 'check_broadcast_status(token)` for network interface

### ISSUE THREAD

**Issue by junha1** [postech-dao/simperby#19]
The node operator would check how well his message is broadcasted, and decide whether to turn off his node.
The return value could be
1. Number of successfully relayed nodes
2. Some kind of a 'score' that considers how well the relayed nodes will actually relay well, according to their past activities.

I think the option 1 will be sufficient for now.

**Comment by lemonholic** [comment]
> 1. Number of successfully relayed nodes

One option: we can make any node directly reply to the sender when they receive a message.
Anyway, I'll think if there is a better way to achieve [1].

> 2. Some kind of a 'score' that considers how well the relayed nodes will actually relay well, according to their past activities.

Do you mean a sort of scoring system where every node is given a score by its peers?
