### ISSUE TITLE
Implement delegation / undelegation

### ISSUE THREAD

**Issue by junha1** [postech-dao/simperby#301]
See [two unimplemented methods](https://github.com/postech-dao/simperby/blob/main/common/src/reserved.rs#L69)
See [here](https://github.com/postech-dao/simperby/blob/main/common/src/reserved.rs#L25) to understand the delegation protocol

**Comment by sigridjineth** [comment]
thks. gonna check this out

**Comment by sigridjineth** [comment]
The PR relates to https://github.com/postech-dao/simperby/pull/303#issuecomment-1399606700
