### ISSUE TITLE
Upgrade Rust version to 1.67

### ISSUE THREAD

**Issue by junha1** [postech-dao/simperby#310]
FYI, this involves numerous clippy errors :)

**Comment by sigridjineth** [comment]
When trying to update the rust version by executing `rustup update` but still shows the same version (not latest version),
then check out the following tips:

```
rustup override set stable
info: using existing install for 'stable-aarch64-apple-darwin'
info: override toolchain for '/Users/sigridjin.eth/Documents/github/simperby' set to 'stable-aarch64-apple-darwin'

  stable-aarch64-apple-darwin unchanged - rustc 1.67.0 (fc594f156 2023-01-24)
```

**Comment by sigridjineth** [comment]
so do I need to wait for the toolchain to be updated to 1.67 version?
