### ISSUE TITLE
Check how PBFT can be safe without lock mechanism

### ISSUE THREAD

**Issue by junha1** [postech-dao/simperby#6]
Compared to Tendermint.

**Comment by byeongjee** [comment]
https://dahliamalkhi.github.io/posts/2018/04/BFT-lens-tndrmnt/#:~:text=TDRMNT%20employs%20a%20two%2Dphase%20voting%20approach%20that%20borrows%20from%20PBFT.%20It%20differs%20from%20PBFT%20in%20a%20locking/unlocking%20scheme%20that%20considerably%20simplifies%20proposer%2Dreplacement%2C%20but%20throttles%20the%20pipeline%20of%20proposals.
